name       : python-pylint-venv
version    : 2.3.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pylint-venv/pylint-venv-2.3.0.tar.gz : 3594955502fdee83c98bfcc8c14cd615e6c7c3608aea525df84853ce79f296bf
homepage   : https://github.com/jgosmann/pylint-venv/
license    : MIT
component  : programming.python
summary    : Make pylint respect virtualenvs
description: |
    Pylint does not respect the currently activated virtualenv if it is not installed in every virtual environment individually. This module provides a Pylint init-hook to use the same Pylint installation with different virtual environments.
builddeps  :
    - python-build
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
